dynamic adding and removal of books done
muhammaduzairrazaq/awesomeBooks pull request #1
Opened 2023-08-24 17:21 UTC by muhammaduzairrazaq

**I have fulfilled the following requirements:**

- Linters added.
- Dynamic adding and removal of books completed.

2023-10-02 12:48 UTC, emhamza requested changes
Hi @muhammaduzairrazaq 
Good job so far but there are some required changes that you need to work on in order to move on to the next part! 🔢 🏁

2023-10-02 12:48 UTC, emhamza commented on script.js
> +  }
Hi @muhammaduzairrazaq 🔢 
Good job so far but I am afraid your onClick event is not working properly. When I tried to add a book in you app the Add button is not working at all. Please fix the potential bug:
![bug](https://github.com/muhammaduzairrazaq/awesomeBooks/assets/122353030/c26d31ab-8166-4935-877b-aad6dc5cde24)

2023-10-02 15:10 UTC, muhammaduzairrazaq commented
**Thanks for reviewing issue resolved :sunglasses: **
![image](https://github.com/muhammaduzairrazaq/awesomeBooks/assets/138608690/d7525328-679e-4d25-95e7-c25f4e41e899)

2023-10-07 09:41 UTC, emhamza approved these changes
Hi 👍 @muhammaduzairrazaq 
Congratulations on this accomplishment. There is nothing to say other than your PR is approved. Its time to marge it. 
🥳

2023-10-15 02:08 UTC, merged